<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>LibDeflate.NET</AssemblyName>
    <PackageId>Unmined.LibDeflate.NET</PackageId>
    <VersionPrefix>1.26.0</VersionPrefix>
    <Authors>jzebedee,megazyz</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/unminednet/Unmined.LibDeflate.NET</PackageProjectUrl>
    <RepositoryUrl>https://github.com/unminednet/Unmined.LibDeflate.NET</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>libdeflate.net libdeflate deflate zlib gzip gz crc32 crc adler32 adler</PackageTags>
    <Description>LibDeflate.NET is a managed wrapper around libdeflate, a native library for fast, whole-buffer DEFLATE-based compression and decompression.</Description>

    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>

    <!-- Optional: Publish the repository URL in the built .nupkg (in the NuSpec <Repository> element) -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup>
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

  <!-- Source Link Support -->
  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.401" PrivateAssets="All" />
  </ItemGroup>

  <!-- Regular dependencies -->
  <ItemGroup>
    <PackageReference Include="Unmined.LibDeflate.Native" Version="1.26.1" />
  </ItemGroup>

</Project>
